apiVersion: apps/v1
kind: Deployment
metadata:
  name: aidoc
  namespace: aidoc-system
  labels:
    app: aidoc
    app.kubernetes.io/name: aidoc
    app.kubernetes.io/part-of: aidoc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aidoc
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: aidoc
    spec:
      containers:
      - name: aidoc
        image: hoffeloffe/aidoc:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "128Mi"
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
        - name: NODE_ENV
          value: "production"
      # ARM-specific configuration for Raspberry Pi
      nodeSelector:
        kubernetes.io/arch: arm64
