apiVersion: v1
kind: Namespace
metadata:
  name: aidoc-system
  labels:
    app.kubernetes.io/part-of: aidoc
    fleet.rancher.io/managed: "true"
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: aidoc-fleet
    meta.helm.sh/release-namespace: aidoc-system
